// Generated by CoffeeScript 1.6.2
(function() {
  var bone, _ref;

  bone = {};

  bone.modules = {};

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    module.exports = bone;
  } else {
    window.bone = bone;
  }

  bone.$ = window.$;

  bone.$(function() {
    return bone.history = new bone.History();
  });

  if (((_ref = window.console) != null ? _ref.log : void 0) != null) {
    bone.log = function() {
      return console.log.apply(console, arguments);
    };
  }

}).call(this);
