// Generated by CoffeeScript 1.6.2
(function() {
  var $;

  $ = bone.$;

  bone.mount = function(selector, templateName, options) {
    var $current, data, info, refresh, sameData, sameTemplate, template, templateString;

    if (options == null) {
      options = {};
    }
    data = options.data;
    refresh = options.refresh;
    if (refresh == null) {
      refresh = false;
    }
    $current = $(selector);
    template = bone.templates[templateName];
    if (data != null) {
      templateString = template(data);
    } else {
      templateString = template();
    }
    if ($current.children().length !== 0) {
      info = $current.data('bone-mount');
      sameTemplate = info.template === templateName;
      sameData = info.data === data;
      if (sameTemplate && sameData && !refresh) {
        return;
      }
      $current.children().remove();
    }
    $current.html(templateString);
    return $current.data('bone-mount', {
      template: templateName,
      data: data
    });
  };

}).call(this);
