// Generated by CoffeeScript 1.6.2
(function() {
  var routeToRegex;

  routeToRegex = function(route) {
    var escapeRegExp, namedParam, optionalParam, splatParam;

    optionalParam = /\((.*?)\)/g;
    namedParam = /(\(\?)?:\w+/g;
    splatParam = /\*\w+/g;
    escapeRegExp = /[\-{}\[\]+?.,\\\^$|#\s]/g;
    route = route.replace(escapeRegExp, "\\$&").replace(optionalParam, "(?:$1)?").replace(namedParam, function(match, optional) {
      if (optional) {
        return match;
      } else {
        return "([^/]+)";
      }
    }).replace(splatParam, "(.*?)");
    return new RegExp("^" + route + "$");
  };

  bone.router = function(options) {
    return $(function() {
      var action, route, _ref;

      _ref = options.routes;
      for (route in _ref) {
        action = _ref[route];
        if (route === 'routes') {
          continue;
        }
        route = routeToRegex(route);
        bone.history.handlers.push({
          route: route,
          callback: options[action],
          router: options
        });
      }
      if (options.initialize != null) {
        return options.initialize();
      }
    });
  };

}).call(this);
