// Generated by CoffeeScript 1.6.2
(function() {
  var bone;

  bone = module.exports = {};

  bone.io = require('./io');

  bone.io.middleware = require('./middleware');

  bone["static"] = require('./static');

  bone.module = require('./module');

}).call(this);
