// Generated by CoffeeScript 1.6.2
(function() {
  var bone, connect;

  connect = require('connect');

  bone = {
    io: {}
  };

  bone.io.middleware = module.exports = {};

  bone.io.middleware.session = function(options) {
    var cookieParser, cookieSecret, secret;

    secret = options.secret;
    cookieSecret = options.cookie.secret;
    cookieParser = connect.cookieParser(cookieSecret);
    return function(data, context, next) {
      var socket;

      socket = context.socket;
      return cookieParser(context, null, function(error) {
        var raw;

        if (error != null) {
          return this.error(error);
        }
        raw = context.cookies['connect.sid'];
        context.sessionID = connect.utils.parseSignedCookie(raw, secret);
        context.sessionStore = options.store;
        return options.store.get(context.sessionID, function(error, session) {
          if (error != null) {
            return this.error(error);
          }
          context.session = new connect.session.Session(context, session);
          return next();
        });
      });
    };
  };

}).call(this);
