// Generated by CoffeeScript 1.6.2
(function() {
  var bone;

  bone = {};

  bone["static"] = require('./static');

  bone.module = module.exports = function(name, path, register) {
    if (register != null) {
      bone["static"].add(path);
    } else {
      register = path;
    }
    return bone.module[name] = register;
  };

}).call(this);
