// Generated by CoffeeScript 1.6.2
(function() {
  var bone, boneScripts, fs, pathutil;

  fs = require('fs');

  pathutil = require('path');

  bone = {};

  boneScripts = {
    "bone.io.js": fs.readFileSync("" + __dirname + "/../../bone.io.js", 'utf8')
  };

  bone["static"] = module.exports = function(options) {
    return function(request, response, next) {
      var contents, scriptName;

      for (scriptName in boneScripts) {
        contents = boneScripts[scriptName];
        if (request.url === ("/bone.io/" + scriptName)) {
          response.set('Content-Type', 'text/javascript');
          return response.send(contents);
        }
      }
      return next();
    };
  };

  bone["static"].add = function(path) {
    return boneScripts[pathutil.basename(path)] = fs.readFileSync(path, 'utf8');
  };

}).call(this);
